#!/bin/bash

db=/home/ubuntu/personal/redditriver/db
db_file=$db/redditriver.db
backup=$db/backup/redditriver.db
dump=$db/log/reddits.log

# reset database
rm -f $db_file
cp $backup $db_file > $dump 2>&1
