#!/bin/bash

sql=/usr/bin/sqlite3
db=/home/ubuntu/personal/redditriver/db
query_stories=$db/stories_stat.sql
query_reddits=$db/subreddits_stat.sql
dump=$db/log/reddits.log
updater=/home/ubuntu/personal/redditriver/bin
updater_stories=$updater/update_stories.py
updater_reddits=$updater/update_subreddits.py


# update subreddits
$sql $db/redditriver.db < $query_reddits > $dump 2>&1
echo "" >> $dump
$updater_reddits >> $dump
$sql $db/redditriver.db < $query_reddits >> $dump 2>&1
echo "===============================" >> $dump
echo "" >> $dump

# update stories
$sql $db/redditriver.db < $query_stories >> $dump 2>&1
ls -sh $db/redditriver.db >> $dump
echo "" >> $dump
$updater_stories >> $dump 2>&1
echo "" >> $dump
$sql $db/redditriver.db < $query_stories >> $dump 2>&1
ls -sh $db/redditriver.db >> $dump
