#!/bin/bash

sql=/usr/bin/sqlite3
db=/home/ubuntu/redditriver/db
db_file=$db/redditriver.db
db_schema=$db/db.schema.txt
query_stories=$db/stories_stat.sql
query_reddits=$db/subreddits_stat.sql
dump=$db/log/reddits.log
updater=/home/ubuntu/redditriver/bin
updater_stories=$updater/update_stories.py
updater_reddits=$updater/update_subreddits.py

# update subreddits
$sql $db_file < $query_reddits >> $dump 2>&1
echo "" >> $dump
$updater_reddits >> $dump 2>&1
$sql $db_file < $query_reddits >> $dump 2>&1
echo "===============================" >> $dump
echo "" >> $dump

# update stories
$sql $db_file < $query_stories >> $dump 2>&1
ls -sh $db_file >> $dump
echo "" >> $dump
$updater_stories >> $dump 2>&1
echo "" >> $dump
$sql $db_file < $query_stories >> $dump 2>&1
ls -sh $db_file >> $dump
